### ISSUE TITLE
TypeError: Limiter.__init__() got multiple values for argument 'key_func'

### ISSUE THREAD

**Issue by ghost** [PaddeCraft/GetiFy#1]
root@ubuntu:~/GetiFy# python3 app.py
Traceback (most recent call last):
  File "/root/GetiFy/app.py", line 52, in <module>
    limiter = Limiter(
TypeError: Limiter.__init__() got multiple values for argument 'key_func'

**Comment by PaddeCraft** [comment]
What version of Flask-Limiter do you have installed? You can check by running `python3 -m pip list | grep Flask-Limiter`.

**Comment by PaddeCraft** [comment]
There was an api change in Flask-Limiter, I added support for the newer versions.

**Comment by ghost** [comment]
I have version 3.2.0
but i am using your updated version and it works fine thanks!
